let cards = [
    { name: "Angular", type: "frontEnd" },
    { name: "C#", logoName: "csharp", type: "backEnd"},
    { name: "Java", type: "backEnd" },
    { name: "Meteor", type: "backEnd" },
    { name: "Python", type: "backEnd" },
    { name: "React", type: "frontEnd" },
    { name: "Vue", type: "frontEnd" },
    { name: "Bootmetro", type: "frontEnd"},
    { name: "Bootstrap", type: "frontEnd"},
    { name: "jQuery", type: "frontEnd"},
    { name: "PHP", type: "backEnd"},
    { name: "Ruby", type: "backEnd"},
    { name: "Bulma", type: "frontEnd"},
    { name: "Foundation", type: "frontEnd"},
    { name: "Material UI", type: "frontEnd"},
    { name: "Materialize", type: "frontEnd"},
    { name: "Milligram", type: "frontEnd"},
    { name: "Semantic UI", type: "frontEnd"},
    { name: "Skeleton", type: "frontEnd"},
    { name: "UIkit", type: "frontEnd"},
    { name: "Laravel", type: "backEnd"},
    { name: "Rails", type: "backEnd"},
    { name: "Symfony", type: "backEnd"},
    { name: "Yii", type: "backEnd"},
    { name: "Phalcon", type: "backEnd"},
    { name: "Backbone.js", logoName:"backbonejs", type: "backEnd"},
    { name: "FuelPHP", type: "backEnd"}
    //{ name: "", type: ""}
];
