let questions = [
    {id: 1, question: "How is communication in Agile development handled?",
      ans1: "It's fluid and happens when a need arises.",
      ans2: "It's specific and only held when definitely needed.",
      ans3: "It's scheduled and requires specific content."},
    {id: 2, question: "Does Agile development value documentation?",
      ans1: "Yes, it does.",
      ans2: "No, it doesn't.",
      ans3: "I don't know."},
    {id: 3, question: "How is the customer involved in Agile development?",
      ans1: "Mainly all the time if wanted.",
      ans2: "Mainly at the beginning.",
      ans3: "Mainly in the end."},
    {id: 4, question: "What is the strength of Agile development?",
      ans1: "Focus on customer features.",
      ans2: "Strategic planning.",
      ans3: "Lots of documentation."},
    {id: 5, question: "When should you use Agile methodology?",
      ans1: "When there isn't a clear picture of the final product.",
      ans2: "When there is a clear picture of the final product.",
      ans3: "When definition, not speed, is key to success."},
    {id: 6, question: "When should you use Agile methodology?",
      ans1: "When rapid production is more important than the quality of the product.",
      ans2: "When there is a clear picture of what the final product should be.",
      ans3: "When definition, not speed, is key to success."},
    {id: 7, question: "In agile development:",
      ans1: "Project priorities are evaluated at the end of each sprint.",
      ans2: "Client has a definite idea of their project.",
      ans3: "There is meticulous record keeping."},
    {id: 8, question: "Disadvantage of Agile development is:",
      ans1: "The final product can be very different from the initial idea.",
      ans2: "Developers can’t go back to a previous stage and make changes.",
      ans3: "The whole product is only tested at the end."},
    {id: 9, question: "Which is not Agile methology?",
      ans1: "Waterfall",
      ans2: "Scrum",
      ans3: "Crystal"},
    {id: 10, question: "What's the highest priority of Agile development?",
      ans1: "Customer satisfaction through early and continuous delivery of valuable software.",
      ans2: "To create best architectures, requirements, and designs from self-organizing teams.",
      ans3: "To make business people and developers work together daily."}
    //more can be added always.
    //template:
    //{id: , question: , ans1: , ans2: , ans3: }
];
