let questions = [
    {id: 2, question: "Does Agile development value documentation?",
      answers: ["Yes, it does.",
                "No, it doesn't.",
                "I don't know."]},
    {id: 3, question: "How is the customer involved in Agile development?",
      answers: ["Mainly all the time if wanted.",
                "Mainly at the beginning.",
                "Mainly in the end."]},
    {id: 4, question: "What is the strength of Agile development?",
      answers: ["Focus on customer features.",
                "Strategic planning.",
                "Lots of documentation."]},
    {id: 7, question: "In agile development:",
      answers: ["Project priorities are evaluated at the end of each sprint.",
                "Client has a definite idea of their project.",
                "There is meticulous record keeping."]},
    {id: 9, question: "Which is not Agile methology?",
      answers: ["Waterfall",
                "Scrum",
                "Crystal"]},
];
